version: "3.1"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: similarweb
      MYSQL_DATABASE: similarweb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 1s
      timeout: 1s
      retries: 5

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8090:8080"

  backend:
    image: node:latest
    restart: always
    environment:
      NODE_ENV: development
      DB_NAME: similarweb
      DB_USER: root
      DB_PASSWORD: similarweb
      DB_HOST: mysql
      DB_DIALECT: mysql
      SERVER_PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["npm", "run", "start"]
    ports:
      - "8080:8080"
